# Generated by Django 5.1.4 on 2026-01-23 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='order_id',
            field=models.CharField(blank=True, help_text='ID from Order Service', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='user_id',
            field=models.CharField(help_text='ID from Auth Service', max_length=255),
        ),
    ]
