apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification
  template:
    metadata:
      labels:
        app: notification
    spec:
      containers:
      - name: notification
        image: miheret217/notification-service:latest 
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
          # Connection string for Prisma
          - name: DATABASE_URL
            value: "postgresql://postgres.ekdjzirbeiakbqpcjhnb:RMfLaxJEkR9kgUYc@aws-1-eu-west-1.pooler.supabase.com:5432/postgres"
          - name: PORT
            value: "3000"
          - name: SERVICE_API_KEY
            value: "ec3c4c82309659eb8328f84e4cb0c163d4514b1c22eb7a94326e01bd5a545bee"
          - name: REDIS_URL
            value: "redis://default:password@redis-service:6379"
          - name: JWT_SECRET
            value: "django-insecure-pharmacy-system-key-2024"
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
spec:
  selector:
    app: notification
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP