apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
      - name: payment
        image: miheret217/payment-service:latest 
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
          - name: DATABASE_URL
            value: "postgres://postgres.ekdjzirbeiakbqpcjhnb:RMfLaxJEkR9kgUYc@aws-1-eu-west-1.pooler.supabase.com:6543/postgres"
          - name: SECRET_KEY
            value: "payment-service-secret-key-123"
          - name: DEBUG
            value: "False"
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
spec:
  selector:
    app: payment
  ports:
    - protocol: TCP
      port: 80        
      targetPort: 8000
  type: ClusterIP