apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
      - name: payment
        # UPDATED TO V2 to ensure the new kafka_consumer.py script is present
        image: miheret217/payment-service:v2 
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
          # --- DATABASE CONNECTION (Supabase) ---
          - name: DATABASE_URL
            value: "postgres://postgres.ekdjzirbeiakbqpcjhnb:RMfLaxJEkR9kgUYc@aws-1-eu-west-1.pooler.supabase.com:6543/postgres"
          
          # --- KAFKA CONFIGURATION (The Asynchronous Bus) ---
          # This is required for the kafka_consumer.py worker to function
          - name: KAFKA_BOOTSTRAP_SERVERS
            value: "kafka-service:9092"

          # --- REDIS CONNECTION ---
          - name: REDIS_URL
            value: "redis://redis-service:6379"
          - name: REDIS_HOST
            value: "redis-service"

          # --- DJANGO SETTINGS ---
          - name: SECRET_KEY
            value: "payment-service-secret-key-123"
          - name: DEBUG
            value: "True"
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
spec:
  selector:
    app: payment
  ports:
    - protocol: TCP
      port: 80        
      targetPort: 8000
  type: ClusterIP
