# Generated by Django 5.1.4 on 2025-12-19 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_is_verified_emailverificationotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('pharmacy', 'Pharmacy'), ('pharmacy_admin', 'Pharmacy Admin'), ('admin', 'Admin')], default='user', max_length=20),
        ),
    ]
