spring.application.name=inventory-service

# Supabase Connection with PgBouncer Fix
spring.datasource.url=jdbc:postgresql://aws-1-eu-west-1.pooler.supabase.com:6543/postgres?sslmode=require&prepareThreshold=0

spring.datasource.username=postgres.ekdjzirbeiakbqpcjhnb
spring.datasource.password=RMfLaxJEkR9kgUYc
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Strategy: Use 'update' so you don't lose your medicines on restart
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# SSL & Hikari Settings
spring.datasource.hikari.data-source-properties.ssl=true
spring.datasource.hikari.data-source-properties.sslfactory=org.postgresql.ssl.NonValidatingFactory

spring.data.redis.host=redis-service
spring.data.redis.port=6379